/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004395",
        "on-surface": "#0b1c30",
        "inverse-primary": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "tertiary-container": "#191c1e",
        "tertiary": "#000000",
        "surface": "#f8f9ff",
        "primary": "#000000",
        "on-tertiary-container": "#818486",
        "on-tertiary-fixed-variant": "#444749",
        "on-tertiary-fixed": "#191c1e",
        "inverse-surface": "#213145",
        "on-error": "#ffffff",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#3f465c",
        "surface-container-low": "#eff4ff",
        "secondary-fixed": "#d8e2ff",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary-container": "#7c839b",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-tint": "#565e74",
        "secondary": "#0058be",
        "background": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "on-secondary-container": "#fefcff",
        "tertiary-fixed": "#e0e3e5",
        "surface-container": "#e5eeff",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#45464d",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#2170e4",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#131b2e",
        "error": "#ba1a1a",
        "outline": "#76777d",
        "on-background": "#0b1c30",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001a42",
        "surface-dim": "#cbdbf5",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bec6e0",
        "primary-container": "#131b2e",
        "inverse-on-surface": "#eaf1ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-padding-mobile": "16px",
        "base": "4px",
        "stack-md": "16px",
        "gutter": "24px",
        "container-padding-desktop": "32px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-desktop": "2rem",
        "margin-mobile": "1rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "mono-sm": ["JetBrains Mono", "monospace"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "mono-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
